explicitly include compiler.h to be sure all stdint types are defined
This fix the following build bug:

  In file included from bertos/emul/emulwin.cpp:43:
  bertos/drv/lcd_gfx_qt.h:74: error: ‘uint8_t’ has not been declared
  make: *** [obj/demo/bertos/emul/emulwin.o] Error 1

git-svn-id: https://src.develer.com/svnoss/bertos/trunk@3130 38d2e660-2303-0410-9eaa-f027e97ec537