USB: max number of endpoints can be equal to the number of interfaces
When only the endpoint 0 is used for a USB device, the number of
endpoints can be equal to the number of interfaces.

This also fixes the following bug in the nightly test build:
  bertos/drv/usb_endpoint.h:77: error: size of array 'STATIC_ASSERTION_FAILED__' is negative

git-svn-id: https://src.develer.com/svnoss/bertos/trunk@4689 38d2e660-2303-0410-9eaa-f027e97ec537