gfx: fix missing dependency.
The file line.c must be a dependency for gfx/text.c. This fixes
"undefined reference to `gfx_rectFillC'" errors.

git-svn-id: https://src.develer.com/svnoss/bertos/trunk@3468 38d2e660-2303-0410-9eaa-f027e97ec537